### ISSUE TITLE
syntax highlighting

### ISSUE THREAD

**Issue by siduck** [jellydn/new-web-app#294]
Hi @jellydn nice work! Ive been looking around to move from docusaurus and use a lighter alternative , does this ssg deal with syntax highlighting of code blocks? like with prism. Docusaurus uses it for syntax highlighting in code blocks https://github.com/PrismJS/prism

**Comment by jellydn** [comment]
Hi @siduck 

I don't understand what issue you're talking about. Is that with `new-web-app` cli or  `docusaurus`? Thanks.

**Comment by siduck** [comment]
> Hi @siduck
> 
> I don't understand what issue you're talking about. Is that with `new-web-app` cli or `docusaurus`? Thanks.

new-web-app . docusaurus uses prism for syntax highlighting . Could you add the same thing in new-web-app?

**Comment by jellydn** [comment]
Are you talking about this document page? https://new-web-app.productsway.com/

**Comment by siduck** [comment]
> Are you talking about this document page? https://new-web-app.productsway.com/

yep , also I just get a counter when I run a fresh build. I was expecting this page https://new-web-app.productsway.com/.

**Comment by siduck** [comment]
Also new-web-app is a static site generator?  this https://new-web-app.productsway.com/ looked a bit similar to docusaurus so I assumed it is

**Comment by siduck** [comment]
oh nvm it , i checked the website dir the the repo and found out that you were using docusaurus.

**Comment by jellydn** [comment]
Hi @siduck 
> Also new-web-app is a static site generator? this [new-web-app.productsway.com](https://new-web-app.productsway.com/) looked a bit similar to docusaurus so i thought it might be one.
Correct. That page is document page for new-web-app cli. Here is the source code. https://github.com/jellydn/new-web-app/blob/main/website/package.json

**Comment by siduck** [comment]
Hm I checked that , docusaurus uses webpack and its heavier on build so I wanted to use something else using vite , found out this and thought its a static site generator :smile: but I was wrong.

**Comment by jellydn** [comment]
:) You could find all vite related on this repo  https://github.com/vitejs/awesome-vite
