### ISSUE TITLE
Support React JS template

### ISSUE THREAD

**Issue by siduck** [jellydn/new-web-app#295]
Hi there! new-web-app's so I suppose it mustnt install the dependencies , it needs to just set the project dir and put the package.json like vite's cli tool does. I use pnpm instead of yarn and its much faster! Also it comes with tsx template by default , how do I use js? :c

**Comment by jellydn** [comment]
Hi @siduck 

Thank you for filing an issue. I could support `pnpm` along with yarn but I don't want to support JS template.

**Comment by siduck** [comment]
> Hi @siduck
> 
> Thank you for filing an issue. I could support `pnpm` along with yarn but I don't want to support JS template.

oh . Idk tsx so asked about it :(

**Comment by jellydn** [comment]
I see. If so, could you open a pull request about it? Thanks

**Comment by siduck** [comment]
> I see. If so, could you open a pull request about it? Thanks

hmm nvm , too dumb of me to assume that this supports ts only lol so I thought i wouldnt be able to do js in it but later realized we can :laughing:
